# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QGui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 883)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.c_input = QtWidgets.QLineEdit(self.centralwidget)
        self.c_input.setMinimumSize(QtCore.QSize(450, 0))
        self.c_input.setObjectName("c_input")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.c_input)
        self.c_button = QtWidgets.QPushButton(self.centralwidget)
        self.c_button.setObjectName("c_button")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.c_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.horizontalLayout.addLayout(self.formLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.q_input = QtWidgets.QComboBox(self.centralwidget)
        self.q_input.setMinimumSize(QtCore.QSize(450, 0))
        self.q_input.setObjectName("q_input")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.q_input)
        self.q_button = QtWidgets.QPushButton(self.centralwidget)
        self.q_button.setObjectName("q_button")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.q_button)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.q_solid_input = QtWidgets.QLineEdit(self.centralwidget)
        self.q_solid_input.setEnabled(False)
        self.q_solid_input.setObjectName("q_solid_input")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.q_solid_input)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.horizontalLayout.addLayout(self.formLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_5)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.c_period_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.c_period_label.setFont(font)
        self.c_period_label.setText("")
        self.c_period_label.setObjectName("c_period_label")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.c_period_label)
        self.c_time_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.c_time_label.setFont(font)
        self.c_time_label.setText("")
        self.c_time_label.setObjectName("c_time_label")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.c_time_label)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.c_upper_factor_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.c_upper_factor_label.setFont(font)
        self.c_upper_factor_label.setText("")
        self.c_upper_factor_label.setObjectName("c_upper_factor_label")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.c_upper_factor_label)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.c_lower_factor_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.c_lower_factor_label.setFont(font)
        self.c_lower_factor_label.setText("")
        self.c_lower_factor_label.setObjectName("c_lower_factor_label")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.c_lower_factor_label)
        self.horizontalLayout_2.addLayout(self.formLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_7)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.q_period_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.q_period_label.setFont(font)
        self.q_period_label.setText("")
        self.q_period_label.setObjectName("q_period_label")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.q_period_label)
        self.q_time_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.q_time_label.setFont(font)
        self.q_time_label.setText("")
        self.q_time_label.setObjectName("q_time_label")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.q_time_label)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.q_upper_factor_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.q_upper_factor_label.setFont(font)
        self.q_upper_factor_label.setText("")
        self.q_upper_factor_label.setObjectName("q_upper_factor_label")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.q_upper_factor_label)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setObjectName("label_21")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.q_lower_factor_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.q_lower_factor_label.setFont(font)
        self.q_lower_factor_label.setText("")
        self.q_lower_factor_label.setObjectName("q_lower_factor_label")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.q_lower_factor_label)
        self.horizontalLayout_2.addLayout(self.formLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Klassiek Algoritme"))
        self.label_3.setText(_translate("MainWindow", "Refactor"))
        self.c_button.setText(_translate("MainWindow", "OK"))
        self.label_4.setText(_translate("MainWindow", "Input"))
        self.label_2.setText(_translate("MainWindow", "Quantum Algoritme"))
        self.q_button.setText(_translate("MainWindow", "OK"))
        self.label_11.setText(_translate("MainWindow", "Refactor"))
        self.q_solid_input.setText(_translate("MainWindow", "15"))
        self.label_6.setText(_translate("MainWindow", "Tijd:"))
        self.label_5.setText(_translate("MainWindow", "Output Klassiek"))
        self.label_8.setText(_translate("MainWindow", "Periode:"))
        self.label_15.setText(_translate("MainWindow", "Factor:"))
        self.label_19.setText(_translate("MainWindow", "Factor:"))
        self.label_9.setText(_translate("MainWindow", "Tijd:"))
        self.label_7.setText(_translate("MainWindow", "Output Quantum"))
        self.label_12.setText(_translate("MainWindow", "Periode:"))
        self.label_17.setText(_translate("MainWindow", "Factor:"))
        self.label_21.setText(_translate("MainWindow", "Factor:"))

